### ISSUE TITLE
Which runtime is being used

### ISSUE THREAD

**Issue by gilv** [pywren/pywren-ibm-cloud#115]
Not sure there is an issue here, perhaps more usage related question.
I created runtime with ./deploy_runtime create cactusone/pywren-dev:3.6 then run our tests with python test/testpywren.py . 
So far tests were using default runtime from the "action_name : pywren-dev_3.6 ".

But when i run tests it printed IBM Cloud Functions init for Runtime: ibmfunctions/action-python-v3.6 - 256MB (Installing...)
so it doesn't use my runtime, but create a new one..

@JosepSampe can you explain this?

**Comment by JosepSampe** [comment]
@gilv Previous action_names were a bit confusing since they didn't include the origin of the runtime (`ibmfunctions/` , `cactusone/` , `jsampe/`), so once deployed, it was impossible to know it. Also, it was not possible to have, for example, these 3 runtimes deployed in the same namespace:
```
ibmfunctions/pywren-dev:3.6
cactusone/pywren-dev:3.6
jsampe/pywren-dev:3.6
```
since they share same `pywren-dev:3.6`

Now, action_name = full_runtime_name. 
Default runtime for python3.6 is:  `ibmfunctions/action-python-v3.6`
As I stated, now to start using pywren there is no need to create/clone anything, since pywren does this job automatically the first time, is for this that it appears `(Installing...)`

If you want to use your self-built runtime, you have 2 options:
Specify the runtime name in the executor:
```
pw = pywren.ibm_cf_executor(runtime='cactusone/pywren-dev:3.6')
```
or add the **runtime** keyword in the config file:
```
ibm_cf:
        runtime:  cactusone/pywren-dev:3.6
```

**Comment by gilv** [comment]
@JosepSampe thanks. great addition.
