### ISSUE TITLE
feature suggestion regarding the partitioner

### ISSUE THREAD

**Issue by omerb01** [pywren/pywren-ibm-cloud#184]
I would like to have a feature to split a dataset into N chunks equally sized.
currently we have `chunk-size` parameter for map executions - I suggest to add another parameter, something like `chunk-n` to do that logic.

edit:
it would be nice also if I will can to extract chunk id inside every action which represents one of N chunks.

**Comment by gilv** [comment]
@omerb01 what is the difference between chunk-size we already have and chunk-n?

**Comment by omerb01** [comment]
@gilv chunk-size divide a COS object into chunks of fixed size, chunk-n is intended to divide a COS object into fixed N chunks equally sized

**Comment by gilv** [comment]
@JosepSampe how complicated to support this?

**Comment by JosepSampe** [comment]
@gilv @omerb01 just a question: when a user provide **chunk_n**, how we have to apply it? What do you expect here? Is **chunk_n** applied individually for each file in the bucket? I mean, if I have 5 files and **chunk_n=3**, each of these 5 files will be split in 3 chunks, right? or should **chunk_n**  be the total number of chunks? In this case, **chunk_n** should always be multiple of N files, since it would be hard to split 5 files in 3 chunks...

**Comment by omerb01** [comment]
@JosepSampe as much like `chunk-size`, I meant for chunking **each** file into n chunks.
but actually it will be useful if we can support both options, I can think about an implementation that gets metadata of all input files in COS and splits them by ranges according to the total sum of bytes. what do you think?

**Comment by JosepSampe** [comment]
@omerb01 I think for the moment I can implement "chunking each file into n chunks".

The other approach might be complicated to implement or not. Not sure right now. Imagine you have 11 files in COS and want only 2 partitions, this means that each function should receive 6 different streams. I don't know if I can concatenate streams in order to be totally transparent to the user that only reads one `data_stream` variable.

**Comment by JosepSampe** [comment]
@omerb01 Done in #214

**Comment by omerb01** [comment]
@JosepSampe it seems that when I add `chunk_n` parameter, it doesn't divide each object into the desired chunks. see #230 for examples in `test_chunks_bucket()` and `test_chunks_bucket_one_reducer_per_object()`

**Comment by JosepSampe** [comment]
@omerb01 What is the size of the files? In order to prevent possible unnecessary chunking, the partitioner is limited to create chunks of at least 1MB

**Comment by omerb01** [comment]
@JosepSampe I tested it with our traditional test files from the script on #230 , we have 5 files there, but only 2 of them are greater than 1MB. when I run the relevant test, I see that only 5 actions launch instead of 7.
b.t.w maybe it's better to let the user define whats the minimum size for chunking, what do you think?

**Comment by omerb01** [comment]
@JosepSampe Thanks!
