### ISSUE TITLE
Question about execution id

### ISSUE THREAD

**Issue by omerb01** [pywren/pywren-ibm-cloud#211]
what is the difference between map `id` here:
https://github.com/pywren/pywren-ibm-cloud/blob/master/examples/map.py
and `obj.part` here:
https://github.com/pywren/pywren-ibm-cloud/blob/master/examples/map_cos_bucket.py

I tried to execute the example with `obj` but got `Partition num: 0` for every action.
do I miss something?

**Comment by JosepSampe** [comment]
@omerb01 
-`id` is the `call_id`. I mean, if you spawn 10 functions, you will get numbers between [0...9].  `id` is generic and you can put it in any function, either processing objects from COS or not.

-In contrast, `obj.part` is the number of partition of the object that is processing that function. In the example, you always see `Partition num: 0` because the object is not split, i.e each function process a entire object, so partition is always 0 since there are no partitions. If you set `chunk_seize`, you will see in `obj.part` the number of the partition for each function-object.

**Comment by omerb01** [comment]
@JosepSampe Thanks, got it.
