### ISSUE TITLE
Odd behaviour when setting globally scoped variables

### ISSUE THREAD

**Issue by robertgo-IBM** [pywren/pywren-ibm-cloud#244]
Following the instructions [here](https://github.com/pywren/pywren-ibm-cloud/blob/master/docs/multiple-parameters.md#common-parameters-across-functions-invocations), observed odd behaviour when setting globally scoped variables inside a class method.

```
(venv) ~> python -V
Python 3.6.5

(venv) ~> pip show pywren-ibm-cloud
Name: pywren-ibm-cloud
Version: 1.3.0
Summary: Run many jobs over IBM Cloud Functions
Home-page: https://github.com/pywren/pywren-ibm-cloud
Author: Gil Vernik
Author-email: gilv@il.ibm.com
License: UNKNOWN
Location: /Users/rg/pycastor/venv/lib/python3.6/site-packages
Requires: pika, requests, tblib, seaborn, kubernetes, matplotlib, lxml, docker, ibm-cos-sdk, pandas, tqdm, glob2, Click, enum34, python-dateutil, PyYAML
Required-by: 

```

*1. Expected behaviour:*

`same_module.py:`

```
import pywren_ibm_cloud as pywren

global_var = None

def my_function(x):
    return global_var

class GlobalScopeTest():

    def set_global_var(self):

        global global_var
        global_var = 'SUCCESS!'

        print('>>> set_global_var(): ' + global_var)

        pw = pywren.ibm_cf_executor()
        pw.map(my_function, [1])

        print('>>> my_function(): ' + str(pw.get_result()))

        pw.clean()

if __name__ == '__main__':
    t = GlobalScopeTest()
    t.set_global_var()
```

```
(venv) ~> python same_module.py
>>> set_global_var(): SUCCESS!
PyWren v1.3.0 init for IBM Cloud Functions - Namespace: RIS Goflex_dev - Region: eu_de
ExecutorID 8c13f7/0 | JobID M000 - Selected Runtime: ibmfunctions/action-python-v3.6 - 256MB 
ExecutorID 8c13f7/0 | JobID M000 - Uploading function and data - Total: 510.0B
ExecutorID 8c13f7/0 | JobID M000 - Starting function invocation: my_function()  - Total: 1 activations
ExecutorID 8c13f7/0 - Getting results...
  100%|████████████| 1/1  
>>> my_function(): SUCCESS!
ExecutorID 8c13f7/0 - Cleaning temporary data
```

`global_var` is set and is visible inside `my_function()`.

*2. Unexpected behaviour:*

`different_module.py`

```
from same_module import GlobalScopeTest

def import_class():
    t = GlobalScopeTest()
    t.set_global_var()

if __name__ == '__main__':
    import_class()
```

```
(venv) ~> python different_module.py
>>> set_global_var(): SUCCESS!
PyWren v1.3.0 init for IBM Cloud Functions - Namespace: RIS Goflex_dev - Region: eu_de
ExecutorID 305049/0 | JobID M000 - Selected Runtime: ibmfunctions/action-python-v3.6 - 256MB 
ExecutorID 305049/0 | JobID M000 - Uploading function and data - Total: 789.0B
ExecutorID 305049/0 | JobID M000 - Starting function invocation: my_function()  - Total: 1 activations
ExecutorID 305049/0 - Getting results...
    100%|████████████| 1/1  
>>> my_function(): []
ExecutorID 305049/0 - Cleaning temporary data
```

In this case, although `global_var` is set, it does not appear to be visible to `my_function()` - perhaps there's an issue with serialisation.

(As a side note, I was attempting to use this approach to get around the `MAX_AGG_DATA_SIZE` limit encountered while passing a comparitively large common parameter to all invocations using `extra_params`).

**Comment by JosepSampe** [comment]
After some test, I can conclude that this is not a possible approach in pywren due to **cloudpickle** library.

When you invoke `same_module.py`, **cloudpickle** detects that the function to serialize is in the same module, so it proceeds to serialize the function itself along with all the variables including the globals. See serialized data:
`b'\x80\x04\x95\xa5\x01\x00\x00\x00\x00\x00\x00\x8c\x17cloudpickle.cloudpickle\x94\x8c\x0e_fill_function\x94\x93\x94(h\x00\x8c\x0f_make_skel_func\x94\x93\x94h\x00\x8c\r_builtin_type\x94\x93\x94\x8c\x08CodeType\x94\x85\x94R\x94(K\x01K\x00K\x01K\x01KCC\x04t\x00S\x00\x94N\x85\x94\x8c\nglobal_var\x94\x85\x94\x8c\x01x\x94\x85\x94\x8c\x0esame_module.py\x94\x8c\x0bmy_function\x94K\x07C\x02\x00\x01\x94))t\x94R\x94J\xff\xff\xff\xff}\x94(\x8c\x0b__package__\x94N\x8c\x08__name__\x94\x8c\x08__main__\x94\x8c\x08__file__\x94\x8c\x0esame_module.py\x94u\x87\x94R\x94}\x94(\x8c\x07globals\x94}\x94h\x0c\x8c\x08SUCCESS!\x94s\x8c\x08defaults\x94N\x8c\x04dict\x94}\x94\x8c\x0eclosure_values\x94N\x8c\x06module\x94h\x18\x8c\x04name\x94h\x11\x8c\x03doc\x94N\x8c\x17_cloudpickle_submodules\x94]\x94\x8c\x08qualname\x94h\x11\x8c\nkwdefaults\x94NutR.'`

When you invoke `same_module.py` from `different_module.py`, **cloudpickle** detects that the function is in another module, since main module is  `different_module.py`,  so it proceeds to serialize only the reference to the function in that module. See serialized data:
`b'\x80\x04\x95\x1f\x00\x00\x00\x00\x00\x00\x00\x8c\x0bsame_module\x94\x8c\x0bmy_function\x94\x93\x94.'`

So that is how cloudpickle works.

**Comment by robertgo-IBM** [comment]
Yes, perhaps it is a nuance of `cloudpickle`.

I also observed that if the `set_global_var()` is defined as a function, rather than as a class method, `global_var` is serialised and visible to `my_function()` from both  `same_module.py` and `different_module.py`. So it appears to relate specifically to the setting of global variables inside class methods.
