### ISSUE TITLE
Separate cloudobjects and temporary objects cleanliness

### ISSUE THREAD

**Issue by omerb01** [pywren/pywren-ibm-cloud#289]
Today, PyWren sets in default: "data_cleaner=True"
so after each operation of `map()` all temporary files that were generated in the process are removed but also all the cloudobjects that were created manually by the user.

I suggest to separate this behavior: automatically remove all temporary files by default ("data_cleaner=True") and also let the user delete his cloudobjects manually, in a user-friendly way outside CF.

what do you think?

**Comment by gilv** [comment]
It even worse... cloudobjects are mixed with PyWren temp objects, so if user need to preserve cloudobjects between invocation, he can't clean temp objects at all. In certain case it generated 1TB of data, where 99% is temp files and few are cloudobjects, and since they all in the same folder we can't clean it.

@JosepSampe can you handle it please? I? guess, we just need to write cloudobjects into different folder and let clean() to delete only temp files. Perhaps we need another method clean_cloudobjects() that will clean them from the new folder

**Comment by JosepSampe** [comment]
@gilv Yep,  but could we verify that all the changes introduced in #288 work properly before adding more changes?

**Comment by JosepSampe** [comment]
I changed the place to store cloudobjects in #290

Now there are 2 options to create cloudobjects:
1. Only passing the data to store:
  `internal_storage.put_object(pickled_data)`
  It will store the cloudobject in:
  `pywren.jobs/cloudobjects/<executor_id>/<job_id>/<call_id>/cloudobject_{x}`
 Now these objects are not deleted when `data_cleaner=True`
 These objects are only deleted when the user executes: `$ pywren-ibm-cloud clean`

2. Specifying a custom location:
  `internal_storage.put_object(pickled_data, bucket='otherbucket', key='somekey')`
  These objects are not deleted when `data_cleaner=True`
  The user is responsible to clean the objects

**Comment by JosepSampe** [comment]
We can extend the `pw.clean()` method so that:
- If you call `pw.clean()` (without args) only the internally managed futures will be deleted.
- If you call `pw.clean(fs=futures_list)`, only the futures will be deleted.
- If you call `pw.clean(cs=cloudobjects_list)` only the Cloud Objects will be deleted.
- If you call `pw.clean(fs=futures_list, cs=cloudobjects_list)` both will be deleted.

**Comment by gilv** [comment]
@JosepSampe yeap...this is very good suggesiton

**Comment by gilv** [comment]
@LachlanStuart does the change implemented by Josep helps in your case?

I changed the place to store cloudobjects in #290

Now there are 2 options to create cloudobjects:

Only passing the data to store:
internal_storage.put_object(pickled_data)
It will store the cloudobject in:
pywren.jobs/cloudobjects/<executor_id>/<job_id>/<call_id>/cloudobject_{x}
Now these objects are not deleted when data_cleaner=True
These objects are only deleted when the user executes: $ pywren-ibm-cloud clean

Specifying a custom location:
internal_storage.put_object(pickled_data, bucket='otherbucket', key='somekey')
These objects are not deleted when data_cleaner=True
The user is responsible to clean the objects

**Comment by LachlanStuart** [comment]
@gilv It does help, but as a user it's slightly different to the behavior I was expecting. 

I believe we've discussed this previously - unnamed CloudObjects are for temporary data being passed between actions, so it would make sense to clean them up at the end of the `FunctionExecutor`'s lifespan*. I think `data_cleaner=True` should be the default, because most users should never need to access the PyWren job objects and will be annoyed if their storage fills up over time with temp files. For this reason, I'd expect `pw.clean()` to clean CloudObjects by default, because `pw.clean()` would have no other purpose in a `data_cleaner=True` world. Possibly there should be an option to stop it e.g. `pw.clean(cloudobjects=False)`, but this would be for advanced users who decide to set `data_cleaner=False`.

\* It's theoretically possible to include this in a `__del__` handler, but people generally avoid doing heavy work in `__del__` methods because they are called at unpredictable times. Typically when a Python classes needs to clean things up when it stops being used, it uses the context manager pattern (i.e. implements [`__enter__` and `__exit__`](https://docs.python.org/3/reference/datamodel.html#object.__enter__) so that it can be used with `with` statements). See [`tempfile.TemporaryFile`](https://docs.python.org/3/library/tempfile.html?highlight=tempdir#tempfile-examples) and [`ThreadPoolExecutor`](https://docs.python.org/3/library/concurrent.futures.html#threadpoolexecutor-example) for examples of how context managers are normally used.

I feel PyWren should move in the direction of working as a context manager so that it has the opportunity to do more complex cleanup like stopping the invoker and cleaning up gracefully if external code has an error and has lost the variable for the executor. You could easily make `FunctionExecutor` work this way, and still be backwards-compatible, with the following additions:

```python
class FunctionExecutor:
    # ...
    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        self.invoker.stop() # Possibly some other cleanup functions need to be called as well
        self.clean()
```

Usage:
```python
with ibm_cf_executor(config) as pw:
    fs = pw.map(...)
    do_something_else()
    result = pw.get_result(fs)
```
The cleanup in `pw.__exit__` is run automatically as soon as execution leaves the `with` block. This means that if there was an unhandled error in `do_something_else` that causes execution to leave this function, PyWren gets the opportunity to clean up and prevent new invocations as soon as the error occurs.

**Comment by JosepSampe** [comment]
I created PR #292 following the comments in this thread.
@gilv @LachlanStuart @omerb01 It is ready to test

**Comment by omerb01** [comment]
@JosepSampe Thanks
