### ISSUE TITLE
dependecies

### ISSUE THREAD

**Issue by Albert65** [pywren/pywren-ibm-cloud#310]
I am wondering how crucial some dependencies might be for pywren-ibm-cloud. After update:
```
ERROR: pywren-ibm-cloud 1.5.2 has requirement ibm-cos-sdk==2.6.0, but you'll have ibm-cos-sdk 2.6.2 which is incompatible.
ERROR: pywren-ibm-cloud 1.5.2 has requirement requests==2.22.0, but you'll have requests 2.23.0 which is incompatible.
```
Also, pywren-ibm-cloud installs idna-2.8, but after update I have idna-2.9 and no complaint. Is that ok?

**Comment by JosepSampe** [comment]
They are not crucial in PyWren, they can be updated. So far I didn't experience any kind of issue with the PyWren dependencies, so they can be all updated, except `pika==0.13.x`.

These deps was pinned in pywren because `ibm-cos-sdk` had an old version of `requests` pinned in its repo, and some time ago after updating `requests` it showed these kind of errors. But seems that now, even pinned, these errors still appear so I will unpin them.

We are not using `idna` in pywren, so it could be a dep of dep.
