### ISSUE TITLE
When some activation fails get_results fails too

### ISSUE THREAD

**Issue by idoyehe** [pywren/pywren-ibm-cloud#33]
Even when one of the activations fails the getting result function fails and throw this error:

    wait(fut_list, executor_id, internal_storage, throw_except)
  File "/action/pywren_ibm_cloud/wait.py", line 69, in wait
  File "/action/pywren_ibm_cloud/wait.py", line 121, in _wait
  File "/action/pywren_ibm_cloud/wait.py", line 121, in <listcomp>
AttributeError: 'NoneType' object has no attribute 'done'

Is this supposed to be like this? I expected it should ignore the failed activations

Thank you

**Comment by gilv** [comment]
This seems to happen when futures is None.
For example one way to reproduce it is to have reducer with signature
def my_reduce_function(results) ( proper way is def my_reduce_function(results, futures) ).
In this case wait.py will fail at 'not_done_futures = [f for f in fs if not f.done]'.

**Comment by JosepSampe** [comment]
Yep, this happens when a future is None. It will also happen when an invocation fails after X retries. @gilv Which should be the correct behaviour? Ignore the failed activations?

**Comment by gilv** [comment]
@JosepSampe perfect point...you are 100% right, this also happens when retry fails.
need to think what is correct behavior in this case.

**Comment by gilv** [comment]
@JosepSampe giving it another thought - let's start that we want to run 100% of actions and we will make longer retries. If some action failed for some reason - we will fail the entire results. I just wonder, can we throw more friendly message that explains "action XYX failed therefore  job is failed" instead of "AttributeError: 'NoneType' object has no attribute 'done'" ;)

**Comment by JosepSampe** [comment]
@gilv Done in Pull #40
