### ISSUE TITLE
clean data from failed job

### ISSUE THREAD

**Issue by gilv** [pywren/pywren-ibm-cloud#81]
I created a bugy code to run over 1000 objects from object storage. 
PyWren generates 1000 tasks and each task will fail. In this case, each task generates status.json and output.pickle , resulting in 2000 objects. 
As Job failed so data was not deleted from the object storage 

We need to fix this so PyWren will cleanup data from all tasks when job is failed.

**Comment by JosepSampe** [comment]
@gilv This is fixed in #122, as long as you have `data_cleaner = True` in config.
https://github.com/pywren/pywren-ibm-cloud/blob/master/pywren_ibm_cloud/wren.py#L318

**Comment by gilv** [comment]
@JosepSampe data_cleaner = True will delete all data from successfull and failed jobs.. I wonder if cleaning partial results of failed jobs is the same as cleaning data from successfull jobs. Is there somethign different we can do with data from failed and successfull jobs? 
I think to generate graphs requires data cleaner to be false, right? this is why we have default data_cleaner = false. Am i correct?

**Comment by JosepSampe** [comment]
@gilv I don't know why default `data_cleaner = false`... In fact it can be `true` since plots can be created anyway. Only in that case you use rabbitmq you need `data_cleaner = False`, becasue then you need to keep statuses in order to print plots, since the statuses are not downloaded trough rabbitmq. But rabbitmq is not the default usage of PyWren, so I think we can move default  `data_cleaner = True`.

Also, I think there is nothing different we can do with failed jobs. PyWren raises the exception and then data_cleaner can be automatically executed.

**Comment by gilv** [comment]
@JosepSampe so should we make the default data_cleaner=True ?

**Comment by JosepSampe** [comment]
@gilv I think so

**Comment by JosepSampe** [comment]
@gilv I think this one can be already close with #233 . Now the data_cleaner() is always executed from any failed job
